name: Build JavaScript

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create JS file with API key
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          mkdir -p assets/js
          cat > assets/js/config.js << EOL
          const config = {
            weatherApiKey: '${{ secrets.WEATHER_API_KEY }}'
          };
          EOL
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add assets/js/config.js
          git commit -m "Update config.js" || exit 0
          git push
