name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create config.js
        run: |
          mkdir -p assets/js
          echo "const config = { weatherApiKey: '${{ secrets.WEATHER_API_KEY }}' };" > assets/js/config.js
          
      - name: Verify file
        run: |
          ls -l assets/js/config.js
          cat assets/js/config.js
          
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/js/config.js
          git commit -m "Update config.js" || echo "No changes to commit"
          git push || echo "No changes to push"
