name: Generate Config

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create config.js
        run: |
          mkdir -p assets/js
          echo "const config = { weatherApiKey: '${{ secrets.WEATHER_API_KEY }}' };" > assets/js/config.js
          
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/js/config.js
          git diff --staged --quiet || git commit -m "Update config.js"
          git push
